chains:
  fantom: https://rpc.ftm.tools
  bsc: https://bsc-dataseed1.binance.org
  polygon: https://polygon-rpc.com

tokens:
  fantom:
    - symbol: FTM            # Gas
    - symbol: USDC
      contract: "0x04068DA6C83AFCFA0e13ba15A6696662335D5B75"
      decimal: 18            # default 18
    - symbol: fUSDT
      contract: "0x049d68029688eAbF473097a2fC38ef61633A3C7A"
  bsc:
    - symbol: BNB
    - symbol: USDC
      contract: "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d"
  polygon:
    - symbol: MATIC

wallets:
  - name: KillerWhale0063
    address: "0x258473a955e900385f984fb3fbfd7480d5949cd7"
    track_for:
      fantom:
        - FTM
        - USDC
      bsc:
        - BNB
        - USDC
    labels:
      type: protocol

