name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "deploy/**"
      - ".github/**"
  workflow_dispatch:

jobs:
  build:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Get short SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Building docker image
        env:
          DOCKER_REGISTRY: docker.pkg.github.com
          DOCKER_REPO: alexakulov/tokenexporter
          DOCKER_IMAGE: tokenexporter
          DOCKER_TAG: ${{ steps.vars.outputs.sha_short }}
          DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USER: ${{ github.actor }}
        run: |
          docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} -f Dockerfile .
          docker image tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_REGISTRY}/${DOCKER_REPO}/${DOCKER_IMAGE}:${DOCKER_TAG}
          docker image tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_REGISTRY}/${DOCKER_REPO}/${DOCKER_IMAGE}:latest
          echo "GITHUB_REF: ${GITHUB_REF##*/}"
          if [[ "${GITHUB_REF##*/}" == "main" && "${EVENT_NAME}" != "pull_request" ]]; then
              echo "Push Docker Image"
              echo ${DOCKER_TOKEN} | docker login -u ${DOCKER_USER} --password-stdin ${DOCKER_REGISTRY}
              docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}/${DOCKER_IMAGE}:${DOCKER_TAG}
              docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}/${DOCKER_IMAGE}:latest
          fi
